### ISSUE TITLE
The Great Renaming 

### ISSUE THREAD

**Issue by IdotMaster1** [bunkercoin/bunkercoin#9]
Yeah we should change Dogecoin ---> Bunkercoin

**Comment by sys-256** [comment]
Ping

**Comment by shruuub** [comment]
> Ping

on0 @sys-256 @sys-256 @sys-256 😃😄🤨👍

**Comment by sys-256** [comment]
MSITER !!!111 😡😡😡😡

**Comment by sys-256** [comment]
@shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub

**Comment by shruuub** [comment]
> @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub @shruuub 

More like cheese 😃 also miser how did the volleyball thibg go :trollsir:

**Comment by sys-256** [comment]
sir

**Comment by sys-256** [comment]
went epic 👍

**Comment by shruuub** [comment]
😃😃😃😃😃😃👍👍👍👍👍👍👍👍

**Comment by IdotMaster1** [comment]
9c7952afec76b6a8030dd97646c9119cc897026b
